### ISSUE TITLE
Понятная инструкция по установке, pls.

### ISSUE THREAD

**Issue by salex72** [perminov-aleksandr/askon-pilot-client-asp#13]
Добрый день!
В настоящее время я провожу опробование системы Pilot-ICE применительно к моей компании, занимающейся разработкой проектно-сметной документации для строительства.

К сожалению, я не могу установить ваш продукт на сервер, так как после прочтения имеющейся инструкции нет очевидного понимания, как это сделать.
Все службы IIS установлены (для пробы) на Windows Server 2008R2. Наш системный администратор уверяет, что всё установлено правильно. Сайт создаётся, но не понятно, какую конкретно папку указывать в качестве физического пути сервера. 
Можете подсказать, как всё-таки правильно установить ваш Web-client?

Спасибо

**Comment by perminov-aleksandr** [comment]
Напишите на почту perminov.a@mail более подробно симптомы неработающего приложения.
